import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.gray5001,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.lightBlue500,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.whiteA70001,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(6.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray10004,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.blueGray90003,
          fontSize: 16.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray80006,
          fontSize: 13.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 10.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        displayLarge: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 52.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        displayMedium: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 40.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        displaySmall: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 36.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        headlineLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 32.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        headlineMedium: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 28.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 25.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: appTheme.gray80006,
          fontSize: 12.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        labelMedium: TextStyle(
          color: appTheme.gray80006,
          fontSize: 10.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        labelSmall: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 8.fSize,
          fontFamily: 'Urbanist',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: appTheme.gray80006,
          fontSize: 20.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.blueGray40004,
          fontSize: 16.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray80006,
          fontSize: 14.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFFFC300),
    primaryContainer: Color(0XFFDA0553),

    // Error colors
    errorContainer: Color(0XFF8F7796),
    onErrorContainer: Color(0XFF1E0F0D),

    // On colors(text colors)
    onPrimary: Color(0XFF222121),
    onPrimaryContainer: Color(0XFF09000B),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber20033 => Color(0X33FAE990);
  Color get amber600 => Color(0XFFF9AF0D);
  Color get amber60001 => Color(0XFFE8B603);
  Color get amber700 => Color(0XFFE59D08);
  Color get amber70001 => Color(0XFFE59E09);
  Color get amber70002 => Color(0XFFF5A000);
  Color get amberA400 => Color(0XFFFFBF00);
  Color get amberA700 => Color(0XFFF7A80F);

  // Black
  Color get black900 => Color(0XFF0B0100);
  Color get black90001 => Color(0XFF1E1001);
  Color get black90002 => Color(0XFF1E1000);
  Color get black90003 => Color(0XFF0C0100);
  Color get black90004 => Color(0XFF080C13);
  Color get black90005 => Color(0XFF051013);
  Color get black90006 => Color(0XFF000000);
  Color get black90066 => Color(0X660B0204);

  // BlackB
  Color get black900B2 => Color(0XB20E0D0D);

  // Blue
  Color get blue100 => Color(0XFFCBE8F9);
  Color get blue10001 => Color(0XFFCAEDFF);
  Color get blue10002 => Color(0XFFC4DFF2);
  Color get blue50 => Color(0XFFDEECF9);
  Color get blue500 => Color(0XFF1D9BF0);
  Color get blue5001 => Color(0XFFE9F6FF);
  Color get blue5002 => Color(0XFFE7F2FD);
  Color get blue5003 => Color(0XFFEAF7FF);
  Color get blue5004 => Color(0XFFEBF5FB);
  Color get blue5005 => Color(0XFFE8F7FF);
  Color get blue5006 => Color(0XFFE8F6FF);
  Color get blue5007 => Color(0XFFE0EFF8);
  Color get blue5008 => Color(0XFFE7F6FF);
  Color get blue900 => Color(0XFF0040BF);
  Color get blueA400 => Color(0XFF1977F3);
  Color get blueA700 => Color(0XFF004FEF);

  // Bluef
  Color get blue507f => Color(0X7FDDF0FA);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray10001 => Color(0XFFCCCCCC);
  Color get blueGray10002 => Color(0XFFCECECE);
  Color get blueGray10003 => Color(0XFFD7D7D7);
  Color get blueGray10004 => Color(0XFFD4D4D4);
  Color get blueGray400 => Color(0XFF8D8C8C);
  Color get blueGray40001 => Color(0XFF868686);
  Color get blueGray40002 => Color(0XFF898989);
  Color get blueGray40003 => Color(0XFF8D8989);
  Color get blueGray40004 => Color(0XFF8E8C8C);
  Color get blueGray40005 => Color(0XFF888888);
  Color get blueGray40006 => Color(0XFF8A8A8A);
  Color get blueGray40007 => Color(0XFF8B8B8B);
  Color get blueGray40008 => Color(0XFF81949E);
  Color get blueGray50 => Color(0XFFEDF0F1);
  Color get blueGray5001 => Color(0XFFF1F1F1);
  Color get blueGray5002 => Color(0XFFF1F2F2);
  Color get blueGray600 => Color(0XFF486484);
  Color get blueGray700 => Color(0XFF525252);
  Color get blueGray800 => Color(0XFF2A3B51);
  Color get blueGray80001 => Color(0XFF2F424D);
  Color get blueGray900 => Color(0XFF322D2D);
  Color get blueGray90001 => Color(0XFF233041);
  Color get blueGray90002 => Color(0XFF233040);
  Color get blueGray90003 => Color(0XFF292E33);
  Color get blueGray90004 => Color(0XFF292D32);
  Color get blueGray90005 => Color(0XFF332238);
  Color get blueGray90006 => Color(0XFF383534);
  Color get blueGray90007 => Color(0XFF2D2D2D);
  Color get blueGray90008 => Color(0XFF3A342E);
  Color get blueGray90099 => Color(0X99362F2F);

  // BlueGrayf
  Color get blueGray1003f => Color(0X3FCFCFCF);

  // BlueGrayc
  Color get blueGray9004c => Color(0X4C12323B);

  // Cyan
  Color get cyan900 => Color(0XFF1F6677);
  Color get cyanA200 => Color(0XFF00FFDD);
  Color get cyanA20001 => Color(0XFF00FFFF);
  Color get cyanA400 => Color(0XFF00DDF4);

  // DeepOrange
  Color get deepOrange300 => Color(0XFFFF7E71);
  Color get deepOrange400 => Color(0XFFFF8B3E);
  Color get deepOrange50 => Color(0XFFF7E8DF);
  Color get deepOrange5001 => Color(0XFFF2EADB);
  Color get deepOrange5002 => Color(0XFFFFEBE6);
  Color get deepOrange700 => Color(0XFFD95B29);
  Color get deepOrange800 => Color(0XFFCC5513);
  Color get deepOrange900 => Color(0XFFA45223);
  Color get deepOrange90001 => Color(0XFFAE430D);
  Color get deepOrange90002 => Color(0XFFBD5B07);
  Color get deepOrange90003 => Color(0XFFCC3300);
  Color get deepOrangeA100 => Color(0XFFFF9B84);

  // DeepPurple
  Color get deepPurple50 => Color(0XFFEEDEFF);
  Color get deepPurple5001 => Color(0XFFEFE7FF);
  Color get deepPurple5002 => Color(0XFFE9E1FF);
  Color get deepPurple600 => Color(0XFF5729BF);
  Color get deepPurpleA100 => Color(0XFFB367FF);
  Color get deepPurpleA10001 => Color(0XFFC97BFD);
  Color get deepPurpleA10002 => Color(0XFF9B71FF);
  Color get deepPurpleA200 => Color(0XFFA838FF);
  Color get deepPurpleA20001 => Color(0XFF9747FF);
  Color get deepPurpleA400 => Color(0XFF6214FF);
  Color get deepPurpleA40001 => Color(0XFF6C31FC);
  Color get deepPurpleA40002 => Color(0XFF7F1CFF);
  Color get deepPurpleA40003 => Color(0XFF6F27FF);
  Color get deepPurpleA700 => Color(0XFF5900CC);

  // Gray
  Color get gray100 => Color(0XFFF2F4F6);
  Color get gray10001 => Color(0XFFEDF3FA);
  Color get gray10002 => Color(0XFFF5EFFF);
  Color get gray10003 => Color(0XFFF0F6F8);
  Color get gray10004 => Color(0XFFF4F4F4);
  Color get gray10005 => Color(0XFFF1F8FA);
  Color get gray200 => Color(0XFFECEBEB);
  Color get gray20001 => Color(0XFFECECEC);
  Color get gray20002 => Color(0XFFEBEBEB);
  Color get gray20003 => Color(0XFFEFEFEF);
  Color get gray20004 => Color(0XFFEFEEED);
  Color get gray20005 => Color(0XFFEAE9E9);
  Color get gray20006 => Color(0XFFE9E7E7);
  Color get gray20007 => Color(0XFFEAEAEA);
  Color get gray300 => Color(0XFFDDDBDB);
  Color get gray30001 => Color(0XFFDAE1E3);
  Color get gray30002 => Color(0XFFE0E0E0);
  Color get gray30003 => Color(0XFFE1E1E1);
  Color get gray30004 => Color(0XFFE8E5E5);
  Color get gray30005 => Color(0XFFD9E1E3);
  Color get gray30006 => Color(0XFFE4E3E3);
  Color get gray30007 => Color(0XFFDEDEDE);
  Color get gray30008 => Color(0XFFDFDDDD);
  Color get gray400 => Color(0XFFC8C4C4);
  Color get gray40001 => Color(0XFFD3C9C2);
  Color get gray40002 => Color(0XFFB1B0B0);
  Color get gray40003 => Color(0XFFBFBDBD);
  Color get gray40004 => Color(0XFFB3B3B3);
  Color get gray40005 => Color(0XFFBFBCBC);
  Color get gray40006 => Color(0XFFB4B4B4);
  Color get gray40007 => Color(0XFFB2B0B0);
  Color get gray40008 => Color(0XFFB1B1B1);
  Color get gray40009 => Color(0XFFBDBDBD);
  Color get gray40010 => Color(0XFFDBC6B9);
  Color get gray40011 => Color(0XFFB4B3B3);
  Color get gray40012 => Color(0XFFC5C5C5);
  Color get gray40013 => Color(0XFFC6BFBF);
  Color get gray40014 => Color(0XFFC0C0C0);
  Color get gray40015 => Color(0XFFBCBBB9);
  Color get gray40016 => Color(0XFFB3AFAF);
  Color get gray50 => Color(0XFFF7FCFF);
  Color get gray500 => Color(0XFFAEA6A6);
  Color get gray50001 => Color(0XFF9C9B9B);
  Color get gray50002 => Color(0XFF939292);
  Color get gray50003 => Color(0XFFA5A7A9);
  Color get gray50004 => Color(0XFF9E8B7D);
  Color get gray50005 => Color(0XFFADADAD);
  Color get gray50006 => Color(0XFFA5A5A5);
  Color get gray50007 => Color(0XFF9E9E9E);
  Color get gray50008 => Color(0XFF999999);
  Color get gray50009 => Color(0XFFA4A7A8);
  Color get gray50010 => Color(0XFFB88783);
  Color get gray50011 => Color(0XFFAEAAAA);
  Color get gray50012 => Color(0XFFA39C9C);
  Color get gray50013 => Color(0XFF9E9999);
  Color get gray50014 => Color(0XFF9B9898);
  Color get gray50015 => Color(0XFFA2A2A2);
  Color get gray50016 => Color(0XFFABA8A8);
  Color get gray50017 => Color(0XFFA5A3A3);
  Color get gray50018 => Color(0XFF939191);
  Color get gray50019 => Color(0XFFA19A9A);
  Color get gray50020 => Color(0XFFA4A3A3);
  Color get gray50021 => Color(0XFFA8A2A2);
  Color get gray50022 => Color(0XFFA3A3A3);
  Color get gray50023 => Color(0XFF9C959E);
  Color get gray50024 => Color(0XFFA7A5A5);
  Color get gray50025 => Color(0XFF929292);
  Color get gray5001 => Color(0XFFF5FAFF);
  Color get gray5002 => Color(0XFFF5F9FB);
  Color get gray5003 => Color(0XFFEFF9FF);
  Color get gray5004 => Color(0XFFF5FBFF);
  Color get gray600 => Color(0XFF828181);
  Color get gray60001 => Color(0XFF86758B);
  Color get gray60002 => Color(0XFF735D79);
  Color get gray60003 => Color(0XFF7F7F7F);
  Color get gray60004 => Color(0XFF808080);
  Color get gray60005 => Color(0XFF7D8271);
  Color get gray60006 => Color(0XFF737373);
  Color get gray60007 => Color(0XFF707B61);
  Color get gray60008 => Color(0XFF898585);
  Color get gray60009 => Color(0XFF838383);
  Color get gray60010 => Color(0XFF726E6E);
  Color get gray60011 => Color(0XFF8B9B75);
  Color get gray60012 => Color(0XFF7E7B7B);
  Color get gray60013 => Color(0XFF818181);
  Color get gray60014 => Color(0XFF6D6A6A);
  Color get gray60015 => Color(0XFF7E8371);
  Color get gray60016 => Color(0XFF747070);
  Color get gray60033 => Color(0X33706F6B);
  Color get gray700 => Color(0XFF61696D);
  Color get gray70001 => Color(0XFF6B6969);
  Color get gray70002 => Color(0XFF666666);
  Color get gray70003 => Color(0XFF5C5C5C);
  Color get gray70004 => Color(0XFF6A6969);
  Color get gray70005 => Color(0XFF676666);
  Color get gray70006 => Color(0XFF626262);
  Color get gray70007 => Color(0XFF6B6568);
  Color get gray70008 => Color(0XFF5B5A5A);
  Color get gray70009 => Color(0XFF686666);
  Color get gray800 => Color(0XFF3F3733);
  Color get gray80000 => Color(0X00453F39);
  Color get gray80001 => Color(0XFF603813);
  Color get gray80002 => Color(0XFF403733);
  Color get gray80003 => Color(0XFF572B15);
  Color get gray80004 => Color(0XFF514E4A);
  Color get gray80005 => Color(0XFF3A3939);
  Color get gray80006 => Color(0XFF4C4C4C);
  Color get gray80007 => Color(0XFF4C4139);
  Color get gray80008 => Color(0XFF4F4F4F);
  Color get gray80009 => Color(0XFF3C3C3C);
  Color get gray80010 => Color(0XFF493C35);
  Color get gray80033 => Color(0X334D4A4A);
  Color get gray900 => Color(0XFF2F1A03);
  Color get gray90001 => Color(0XFF5B1500);
  Color get gray90002 => Color(0XFF361603);
  Color get gray90003 => Color(0XFF232323);
  Color get gray90004 => Color(0XFF241904);
  Color get gray90005 => Color(0XFF421B18);
  Color get gray90006 => Color(0XFF253B06);
  Color get gray90007 => Color(0XFF421A03);
  Color get gray90008 => Color(0XFF152232);
  Color get gray90009 => Color(0XFF221501);
  Color get gray90010 => Color(0XFF0F1622);
  Color get gray90011 => Color(0XFF301A04);
  Color get gray90012 => Color(0XFF150E17);
  Color get gray90013 => Color(0XFF1E1E1E);
  Color get gray90014 => Color(0XFF221825);
  Color get gray90015 => Color(0XFF240D1C);
  Color get gray90016 => Color(0XFF232222);
  Color get gray90017 => Color(0XFF17191C);
  Color get gray90018 => Color(0XFF111B28);
  Color get gray90019 => Color(0XFF1C121F);
  Color get gray90020 => Color(0XFF1B0C19);
  Color get gray90021 => Color(0XFF111C28);
  Color get gray90059 => Color(0X59191D1F);

  // Grayf
  Color get gray8007f => Color(0X7F474545);

  // Grayc
  Color get gray9004c => Color(0X4C333A07);
  Color get gray9004c01 => Color(0X4C050C2E);

  // GrayB
  Color get gray900B2 => Color(0XB21A1919);
  Color get gray900B201 => Color(0XB21B1919);
  Color get gray900B202 => Color(0XB2151414);

  // Green
  Color get greenA700 => Color(0XFF14DB40);

  // Indigo
  Color get indigo50 => Color(0XFFE4E8EB);
  Color get indigo500 => Color(0XFF314FBA);
  Color get indigo800 => Color(0XFF1A4688);

  // Indigof
  Color get indigo9000f => Color(0X0F103580);

  // LightBlue
  Color get lightBlue400 => Color(0XFF31B5FF);
  Color get lightBlue50 => Color(0XFFE9F8FF);
  Color get lightBlue500 => Color(0XFF10A7FC);
  Color get lightBlue5001 => Color(0XFFD7F2FF);
  Color get lightBlue700 => Color(0XFF0A89D2);
  Color get lightBlue70001 => Color(0XFF0091C4);
  Color get lightBlue800 => Color(0XFF0073B5);
  Color get lightBlueA200 => Color(0XFF38B6FF);
  Color get lightBlueA400 => Color(0XFF00C3FF);
  Color get lightBlueA700 => Color(0XFF0193E5);
  Color get lightBlueA70001 => Color(0XFF0294E5);

  // LightGreen
  Color get lightGreen100 => Color(0XFFEAE0C7);
  Color get lightGreen200 => Color(0XFFD8CBA4);
  Color get lightGreen50 => Color(0XFFF3FBE6);
  Color get lightGreen5001 => Color(0XFFECFFD6);
  Color get lightGreen5002 => Color(0XFFEFF9DF);
  Color get lightGreenA100 => Color(0XFFCAF888);

  // Lime
  Color get lime100 => Color(0XFFF2EAC2);
  Color get lime10001 => Color(0XFFF3F0C9);
  Color get lime10002 => Color(0XFFEEF6CF);
  Color get lime10003 => Color(0XFFE7F6D1);
  Color get lime200 => Color(0XFFDBF9AE);
  Color get lime20066 => Color(0X66EFDB9F);
  Color get lime50 => Color(0XFFEFFFD8);
  Color get lime5001 => Color(0XFFF4FDE8);
  Color get lime900 => Color(0XFF775105);
  Color get lime90000 => Color(0X00733D03);
  Color get lime90001 => Color(0XFF895809);
  Color get lime90002 => Color(0XFFA8632A);
  Color get lime90003 => Color(0XFF8C5325);
  Color get lime90004 => Color(0XFF99600A);
  Color get lime90005 => Color(0XFF955725);
  Color get lime90006 => Color(0XFF9A6705);
  Color get lime90007 => Color(0XFFA06C04);

  // Orange
  Color get orange100 => Color(0XFFF7DFC1);
  Color get orange10001 => Color(0XFFF4E0B6);
  Color get orange10002 => Color(0XFFF3E1A6);
  Color get orange50 => Color(0XFFFFF6E4);
  Color get orange500 => Color(0XFFEA990C);
  Color get orange5001 => Color(0XFFFFF3E3);
  Color get orange5002 => Color(0XFFFCF2E8);
  Color get orange5003 => Color(0XFFF9F1D2);
  Color get orange700 => Color(0XFFE78007);
  Color get orange70001 => Color(0XFFE58900);
  Color get orange800 => Color(0XFFDE6E08);
  Color get orange80001 => Color(0XFFF56D00);
  Color get orange80002 => Color(0XFFD36900);
  Color get orangeA200 => Color(0XFFF7A63A);
  Color get orangeA700 => Color(0XFFF8600E);

  // Orangec
  Color get orange504c => Color(0X4CFFEDD8);

  // Pink
  Color get pink700 => Color(0XFFBE2F55);
  Color get pink800 => Color(0XFFA20074);
  Color get pink900 => Color(0XFF991538);
  Color get pink90001 => Color(0XFF781E36);
  Color get pink90066 => Color(0X66801B34);
  Color get pinkA70072 => Color(0X72CF0696);

  // Purple
  Color get purple50 => Color(0XFFEFDAFF);
  Color get purple600 => Color(0XFF8E3D9C);
  Color get purple60001 => Color(0XFF9500AF);
  Color get purple900 => Color(0XFF66007F);
  Color get purpleA100 => Color(0XFFFF71E3);
  Color get purpleA400 => Color(0XFFCA00F4);
  Color get purpleA40001 => Color(0XFFDB00D3);
  Color get purpleA40002 => Color(0XFFDF14FF);
  Color get purpleA700 => Color(0XFFAC00F4);
  Color get purpleA70001 => Color(0XFFB720FF);
  Color get purpleA70002 => Color(0XFFA000F4);

  // Red
  Color get red500 => Color(0XFFFF3333);
  Color get red50001 => Color(0XFFEA4335);
  Color get red600 => Color(0XFFDA3736);
  Color get redA100 => Color(0XFFFF897E);
  Color get redA400 => Color(0XFFFF2B44);
  Color get redA700 => Color(0XFFDF0C0C);

  // Redc
  Color get red9004c => Color(0X4C8D2504);

  // Teal
  Color get teal50 => Color(0XFFE0E9EF);
  Color get teal5001 => Color(0XFFDEE6EF);
  Color get teal600 => Color(0XFF008080);
  Color get tealA700 => Color(0XFF00CCB1);
  Color get tealA70001 => Color(0XFF13C69C);
  Color get tealA70002 => Color(0XFF00BCA1);

  // White
  Color get whiteA700 => Color(0XFFFFFEFD);
  Color get whiteA70001 => Color(0XFFFFFFFF);

  // Yellow
  Color get yellow100 => Color(0XFFFFEDCD);
  Color get yellow10001 => Color(0XFFFFEDC0);
  Color get yellow10033 => Color(0X33FFF4BB);
  Color get yellow400 => Color(0XFFF5F550);
  Color get yellow40001 => Color(0XFFF5F851);
  Color get yellow50 => Color(0XFFFFFDDE);
  Color get yellow500 => Color(0XFFFFEA27);
  Color get yellow700 => Color(0XFFFFB81F);
  Color get yellow70033 => Color(0X33E3C41D);
  Color get yellow800 => Color(0XFFFEA917);
  Color get yellow80001 => Color(0XFFF89D14);
  Color get yellow80002 => Color(0XFFFAAF1F);
  Color get yellow80003 => Color(0XFFFFB61D);
  Color get yellow900 => Color(0XFFDA921D);
  Color get yellow90001 => Color(0XFFC98516);
  Color get yellow90002 => Color(0XFFFF8E26);
  Color get yellow90003 => Color(0XFFDD8628);
  Color get yellowA200 => Color(0XFFEEFF00);
  Color get yellowA20000 => Color(0X00FAFF0E);
  Color get yellowA20001 => Color(0XFFEEF901);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
