import 'controller/activities_controller.dart';import 'package:flutter/material.dart';import 'package:muhammad_zubair_s_application3/core/app_export.dart';class ActivitiesScreen extends GetWidget<ActivitiesController> {const ActivitiesScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(height: 808.v, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 16.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGroup1000003916Blue5001, height: 284.v, width: 134.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(top: 10.v)), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_combat_pack".tr, style: CustomTextStyles.titleSmallSemiBold15)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 23.h), child: Text("msg_coming_out_on_27_06".tr, style: CustomTextStyles.labelLargeGray50018)), SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgPngegg31, height: 138.v, width: 387.h, radius: BorderRadius.circular(30.h)), SizedBox(height: 24.v), _buildFishHunters()]))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgArrowdownGray80002, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgArrowLeft();}), Padding(padding: EdgeInsets.only(left: 131.h, bottom: 3.v), child: Text("lbl_activities".tr, style: CustomTextStyles.titleSmallSemiBold15))])))])))); } 
/// Section Widget
Widget _buildFishHunters() { return Container(padding: EdgeInsets.symmetric(horizontal: 14.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_fish_hunters".tr, style: CustomTextStyles.titleSmallSemiBold15)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("msg_coming_out_on_27_06".tr, style: CustomTextStyles.labelLargeGray50018)), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgScreen11, height: 150.v, width: 353.h, radius: BorderRadius.circular(10.h)), SizedBox(height: 26.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_bravery_greed".tr, style: CustomTextStyles.titleSmallSemiBold15), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("msg_coming_out_on_27_06".tr, style: CustomTextStyles.labelLargeGray50018))])])), SizedBox(height: 9.v), CustomImageView(imagePath: ImageConstant.imgCapture1, height: 150.v, width: 353.h, radius: BorderRadius.circular(10.h), margin: EdgeInsets.only(left: 6.h))])); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
