import '../following_screen/widgets/userprofile8_item_widget.dart';import 'controller/following_controller.dart';import 'models/userprofile8_item_model.dart';import 'package:flutter/material.dart';import 'package:muhammad_zubair_s_application3/core/app_export.dart';import 'package:muhammad_zubair_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:muhammad_zubair_s_application3/widgets/app_bar/appbar_subtitle_one.dart';import 'package:muhammad_zubair_s_application3/widgets/app_bar/appbar_trailing_image.dart';import 'package:muhammad_zubair_s_application3/widgets/app_bar/custom_app_bar.dart';class FollowingScreen extends GetWidget<FollowingController> {const FollowingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Padding(padding: EdgeInsets.only(left: 20.h, top: 22.v, right: 20.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 12.v);}, itemCount: controller.followingModelObj.value.userprofile8ItemList.value.length, itemBuilder: (context, index) {Userprofile8ItemModel model = controller.followingModelObj.value.userprofile8ItemList.value[index]; return Userprofile8ItemWidget(model);}))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowdownGray80002, margin: EdgeInsets.only(left: 20.h), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleOne(text: "lbl_following".tr, margin: EdgeInsets.only(left: 131.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewindGray80002, margin: EdgeInsets.symmetric(horizontal: 20.h))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
