import '../../../core/app_export.dart';import 'frame2_item_model.dart';import 'frame3_item_model.dart';import 'frame4_item_model.dart';import 'frame5_item_model.dart';/// This class defines the variables used in the [countries_screen],
/// and is typically used to hold data that is passed between different parts of the application.
class CountriesModel {Rx<List<Frame2ItemModel>> frame2ItemList = Rx([Frame2ItemModel(argentina: "Argentina".obs),Frame2ItemModel(argentina: "Aland".obs),Frame2ItemModel(argentina: "Albania".obs),Frame2ItemModel(argentina: "Algeria".obs),Frame2ItemModel(argentina: "Samoa".obs),Frame2ItemModel(argentina: "Almenia".obs),Frame2ItemModel(argentina: "Belgium".obs),Frame2ItemModel(argentina: "USA".obs),Frame2ItemModel(argentina: "Australia".obs),Frame2ItemModel(argentina: "Ghana".obs),Frame2ItemModel(argentina: "Almenia".obs),Frame2ItemModel(argentina: "Belgium".obs),Frame2ItemModel(argentina: "USA".obs),Frame2ItemModel(argentina: "Australia".obs),Frame2ItemModel(argentina: "Ghana".obs),Frame2ItemModel(argentina: "Almenia".obs),Frame2ItemModel(argentina: "Belgium".obs),Frame2ItemModel(argentina: "USA".obs),Frame2ItemModel(argentina: "Australia".obs),Frame2ItemModel(argentina: "Ghana".obs)]);

Rx<List<Frame3ItemModel>> frame3ItemList = Rx([Frame3ItemModel(argentinaText: "Argentina".obs),Frame3ItemModel(argentinaText: "Aland".obs),Frame3ItemModel(argentinaText: "Albania".obs),Frame3ItemModel(argentinaText: "Algeria".obs),Frame3ItemModel(argentinaText: "Samoa".obs),Frame3ItemModel(argentinaText: "Almenia".obs),Frame3ItemModel(argentinaText: "Belgium".obs),Frame3ItemModel(argentinaText: "USA".obs),Frame3ItemModel(argentinaText: "Australia".obs),Frame3ItemModel(argentinaText: "Ghana".obs),Frame3ItemModel(argentinaText: "Almenia".obs),Frame3ItemModel(argentinaText: "Belgium".obs),Frame3ItemModel(argentinaText: "USA".obs),Frame3ItemModel(argentinaText: "Australia".obs),Frame3ItemModel(argentinaText: "Ghana".obs),Frame3ItemModel(argentinaText: "Almenia".obs),Frame3ItemModel(argentinaText: "Belgium".obs),Frame3ItemModel(argentinaText: "USA".obs),Frame3ItemModel(argentinaText: "Australia".obs),Frame3ItemModel(argentinaText: "Ghana".obs)]);

Rx<List<Frame4ItemModel>> frame4ItemList = Rx([Frame4ItemModel(argentinaText: "Argentina".obs),Frame4ItemModel(argentinaText: "Aland".obs),Frame4ItemModel(argentinaText: "Albania".obs),Frame4ItemModel(argentinaText: "Algeria".obs),Frame4ItemModel(argentinaText: "Samoa".obs),Frame4ItemModel(argentinaText: "Almenia".obs),Frame4ItemModel(argentinaText: "Belgium".obs),Frame4ItemModel(argentinaText: "USA".obs),Frame4ItemModel(argentinaText: "Australia".obs),Frame4ItemModel(argentinaText: "Ghana".obs),Frame4ItemModel(argentinaText: "Almenia".obs),Frame4ItemModel(argentinaText: "Belgium".obs),Frame4ItemModel(argentinaText: "USA".obs),Frame4ItemModel(argentinaText: "Australia".obs),Frame4ItemModel(argentinaText: "Ghana".obs),Frame4ItemModel(argentinaText: "Almenia".obs),Frame4ItemModel(argentinaText: "Belgium".obs),Frame4ItemModel(argentinaText: "USA".obs),Frame4ItemModel(argentinaText: "Australia".obs),Frame4ItemModel(argentinaText: "Ghana".obs)]);

Rx<List<Frame5ItemModel>> frame5ItemList = Rx([Frame5ItemModel(argentinaText: "Argentina".obs),Frame5ItemModel(argentinaText: "Aland".obs),Frame5ItemModel(argentinaText: "Albania".obs),Frame5ItemModel(argentinaText: "Algeria".obs),Frame5ItemModel(argentinaText: "Samoa".obs),Frame5ItemModel(argentinaText: "Almenia".obs),Frame5ItemModel(argentinaText: "Belgium".obs),Frame5ItemModel(argentinaText: "USA".obs),Frame5ItemModel(argentinaText: "Australia".obs),Frame5ItemModel(argentinaText: "Ghana".obs)]);

 }
