import '../../../core/app_export.dart';import 'communitycard_item_model.dart';import 'viewhierarchysection_item_model.dart';import 'fatherdaycomponentgrid_item_model.dart';/// This class defines the variables used in the [community_one_page],
/// and is typically used to hold data that is passed between different parts of the application.
class CommunityOneModel {Rx<List<CommunitycardItemModel>> communitycardItemList = Rx([CommunitycardItemModel(image:ImageConstant.imgRectangle8164x64.obs,title: "Hot boys Crew".obs,image1:ImageConstant.imgClose16x16.obs,description: "This community is to make everyo ...".obs,membersCount: "120k members".obs),CommunitycardItemModel(image:ImageConstant.imgRectangle812.obs,description: "This community is to make everyo ...".obs,membersCount: "10k members".obs),CommunitycardItemModel(image:ImageConstant.imgRectangle813.obs,title: "Earn and win".obs,image1:ImageConstant.imgClose16x16.obs,description: "This community is to make everyo ...".obs,membersCount: "10k members".obs)]);

Rx<List<ViewhierarchysectionItemModel>> viewhierarchysectionItemList = Rx([ViewhierarchysectionItemModel(image1:ImageConstant.imgRectangle86.obs,text1: "12K".obs,text2: "Music concert".obs),ViewhierarchysectionItemModel(image1:ImageConstant.imgRectangle86138x196.obs,text1: "12K".obs)]);

Rx<List<FatherdaycomponentgridItemModel>> fatherdaycomponentgridItemList = Rx([FatherdaycomponentgridItemModel(fatherImage:ImageConstant.imgRectangle85.obs,fatherText: "Father’s Day".obs,fatherImage1:ImageConstant.imgDragon.obs,clockImage:ImageConstant.imgClockLightBlue500.obs,clockText: "1d 24h 6m".obs),FatherdaycomponentgridItemModel(fatherImage:ImageConstant.imgRectangle85110x170.obs,fatherText: "Chess 3d".obs,fatherImage1:ImageConstant.imgClose16x16.obs,clockImage:ImageConstant.imgClockLightBlue500.obs,clockText: "2h 6m".obs),FatherdaycomponentgridItemModel(fatherImage:ImageConstant.imgRectangle85.obs,fatherText: "Father’s Day".obs,fatherImage1:ImageConstant.imgDragon.obs,clockImage:ImageConstant.imgEye.obs,clockText: "1d 24h 6m".obs),FatherdaycomponentgridItemModel(fatherImage:ImageConstant.imgRectangle85.obs,fatherText: "Father’s Day".obs,fatherImage1:ImageConstant.imgDragon.obs,clockImage:ImageConstant.imgEye.obs,clockText: "1d 24h 6m".obs)]);

 }
