import '../level_screen/widgets/frame8_item_widget.dart';import '../level_screen/widgets/viewhierarchy1_item_widget.dart';import 'controller/level_controller.dart';import 'models/frame8_item_model.dart';import 'models/viewhierarchy1_item_model.dart';import 'package:flutter/material.dart';import 'package:muhammad_zubair_s_application3/core/app_export.dart';import 'package:muhammad_zubair_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:muhammad_zubair_s_application3/widgets/app_bar/appbar_title.dart';import 'package:muhammad_zubair_s_application3/widgets/app_bar/custom_app_bar.dart';class LevelScreen extends GetWidget<LevelController> {const LevelScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 38.v), child: Padding(padding: EdgeInsets.only(left: 19.h, right: 19.h, bottom: 5.v), child: Column(children: [_buildFrameLvTen(), SizedBox(height: 13.v), Align(alignment: Alignment.centerRight, child: Container(height: 32.v, width: 50.h, margin: EdgeInsets.only(right: 70.h), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCheckmarkGray8000232x50, height: 32.v, width: 50.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Text("lbl_75".tr, style: CustomTextStyles.labelLargeBold))]))), SizedBox(height: 3.v), Container(height: 10.v, width: 353.h, decoration: BoxDecoration(color: appTheme.gray5002, borderRadius: BorderRadius.circular(5.h)), child: ClipRRect(borderRadius: BorderRadius.circular(5.h), child: LinearProgressIndicator(value: 0.65, backgroundColor: appTheme.gray5002))), SizedBox(height: 3.v), _buildFrameRow(), SizedBox(height: 43.v), _buildFrameColumn(), SizedBox(height: 35.v), _buildFrameColumn1()])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowdownGray80002, margin: EdgeInsets.only(left: 20.h), onTap: () {onTapArrowLeft();}), actions: [AppbarTitle(text: "lbl_level".tr, margin: EdgeInsets.fromLTRB(146.h, 2.v, 164.h, 2.v))]); } 
/// Section Widget
Widget _buildFrameLvTen() { return SizedBox(height: 190.v, width: 353.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgRectangle5980, height: 128.v, width: 353.h, radius: BorderRadius.circular(10.h), alignment: Alignment.topCenter), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 125.h), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 95.v, width: 91.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgEllipse3891x91, height: 91.adaptSize, width: 91.adaptSize, radius: BorderRadius.circular(45.h), alignment: Alignment.topCenter), Align(alignment: Alignment.bottomCenter, child: Container(width: 37.h, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 1.v), decoration: AppDecoration.gradientPrimaryToAmberA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Text("lbl_lv_10".tr, style: CustomTextStyles.labelMediumWhiteA70001SemiBold_3)))])), SizedBox(height: 10.v), Text("lbl_sarah_wegan".tr, style: CustomTextStyles.titleMediumGray80006SemiBold)])))])); } 
/// Section Widget
Widget _buildFrameRow() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_level_10".tr, style: theme.textTheme.labelLarge), Text("lbl_1200_1800".tr, style: theme.textTheme.labelLarge)]); } 
/// Section Widget
Widget _buildFrameColumn() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 118.h), child: Text("lbl_medal_reward".tr, style: CustomTextStyles.titleSmall15)), SizedBox(height: 13.v), Obx(() => Wrap(runSpacing: 18.v, spacing: 18.h, children: List<Widget>.generate(controller.levelModelObj.value.frame8ItemList.value.length, (index) {Frame8ItemModel model = controller.levelModelObj.value.frame8ItemList.value[index]; return Frame8ItemWidget(model);})))]); } 
/// Section Widget
Widget _buildFrameColumn1() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 99.h), child: Text("lbl_pendant_reward".tr, style: CustomTextStyles.titleSmall15)), SizedBox(height: 13.v), Column(children: [Padding(padding: EdgeInsets.only(left: 31.h, right: 27.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 108.v, width: 141.h, margin: EdgeInsets.only(bottom: 8.v), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPngegg121, height: 92.v, width: 141.h, alignment: Alignment.topCenter), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 33.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgEllipse45, height: 75.adaptSize, width: 75.adaptSize, radius: BorderRadius.circular(37.h)), SizedBox(height: 6.v), Text("lbl_level_99_110".tr, style: theme.textTheme.labelLarge)])))])), Padding(padding: EdgeInsets.only(left: 26.h, top: 3.v), child: Column(children: [SizedBox(height: 97.v, width: 96.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPngegg111, height: 97.v, width: 96.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgEllipse44, height: 69.adaptSize, width: 69.adaptSize, radius: BorderRadius.circular(34.h), alignment: Alignment.center)])), SizedBox(height: 1.v), Text("lbl_level_88_98".tr, style: theme.textTheme.labelLarge)]))])), SizedBox(height: 23.v), SizedBox(height: 102.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 32.h);}, itemCount: controller.levelModelObj.value.viewhierarchy1ItemList.value.length, itemBuilder: (context, index) {Viewhierarchy1ItemModel model = controller.levelModelObj.value.viewhierarchy1ItemList.value[index]; return Viewhierarchy1ItemWidget(model);})))])])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
